### PR TITLE
Fix player being teleported to [0, 0, 0] ...

### LINKED ISSUE #27: Dimensional cake teleport to the wrong position
**Pack Version:**
latest-dev-2dd8f8a

**Description:**
Dimensional cake teleport to the position (0, 0, 0), breaking the bedrock and then fall out of the world.

**Steps To Reproduce:**
eat the cake, first teleport everything is fine
use `/spawn` or` /home` teleport to other dimension
eat same cake again, it will send me to position 0,0,0
Nether Cake and End Cake have same problem

use `/de invalidate PlayerName 0`
in Void dimension eat Overworld Cake, use `/home` back and use Overworld Cake again
Overworld Cake also has the same problem

But, if I do not use `/home` `/spawn`, Forced to use cake to teleport back, then everything is fine
Even if you use `/home` `/spawn` again

### PR DESCRIPTION
**Pull request by serenibyss**
when something other than a cake is used to teleport between dimensions

Closes #27

### CODE REVIEW

File: src/main/java/jackyy/dimensionaledibles/util/TeleporterHandler.java [hunk 1]
```diff
@@ -120,20 +120,22 @@ public static void updateDimPos(EntityPlayer player, int dimension, BlockPos pos
     public static BlockPos getDimPos(EntityPlayerMP player, int dimension, BlockPos currentPos) {
         NBTTagCompound dimensionCache = getModNBTData(player);
         NBTTagCompound dimPos = (NBTTagCompound) dimensionCache.getTag("" + dimension);
-        BlockPos position;
         if (dimPos == null) {
             dimPos = new NBTTagCompound();
             dimensionCache.setTag("" + dimension, dimPos);
+        }
+        BlockPos position = new BlockPos(dimPos.getInteger("x"), dimPos.getInteger("y"), dimPos.getInteger("z"));
```
Comment (ALongStringOfNumbers) [inline src/main/java/jackyy/dimensionaledibles/util/TeleporterHandler.java:127]: Could fetching here cause an issue if the dimension position was just created? If `dimPos` was null, it will be initialized as a new NBTTagCompound, which would not have any stored x/y/z coordinate positions yet

Comment (Exaxxion) [reply src/main/java/jackyy/dimensionaledibles/util/TeleporterHandler.java:127]: If it was just created, then all fields will resolve to the default value of `0`. Since we only care about the Y position being greater than zero, this should work fine.

**Review by Exaxxion — APPROVED** [review]
